### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by janl** [hoodiehq/hoodie-plugins-manager#17]
I’m trying to release a new version but the tests fail, even on older states, even the 0.2.6 release:

```
> npm test
...
✖ #1 multiple addSource calls

AssertionError: 3 == 1
    at Object.equal (/Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/lib/types.js:83:39)
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/test/test-plugin-api.js:468:22
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/hoodie-plugins-api/node_modules/couchr/couchr-node.js:184:32
    at process._tickDomainCallback (node.js:486:13)

Error: Expected 9 assertions, 25 ran
    at test.done (/Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/lib/types.js:121:25)
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/lib/core.js:218:25
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/deps/async.js:168:13
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/deps/async.js:131:25
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/deps/async.js:165:17
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/deps/async.js:463:34
    at MultiCouch.<anonymous> (/Users/jan/Work/hoodie/hoodie-plugins-manager/test/lib/utils.js:30:9)
    at MultiCouch.g (events.js:180:16)
    at MultiCouch.emit (events.js:92:17)
    at MultiCouch.stop (/Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/multicouch/lib/multicouch.js:126:10)

Error: not_found
deleted
    at IncomingMessage.<anonymous> (/Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/hoodie-plugins-api/node_modules/couchr/couchr-node.js:168:35)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)

✖ #1 multiple addSource calls

AssertionError: 3 == 1
    at Object.equal (/Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/lib/types.js:83:39)
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/test/test-plugin-api.js:468:22
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/hoodie-plugins-api/node_modules/couchr/couchr-node.js:184:32
    at process._tickDomainCallback (node.js:486:13)

Error: Expected 9 assertions, 25 ran
    at test.done (/Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/lib/types.js:121:25)
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/lib/core.js:218:25
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/deps/async.js:168:13
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/deps/async.js:131:25
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/deps/async.js:165:17
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/deps/async.js:463:34
    at MultiCouch.<anonymous> (/Users/jan/Work/hoodie/hoodie-plugins-manager/test/lib/utils.js:30:9)
    at MultiCouch.g (events.js:180:16)
    at MultiCouch.emit (events.js:92:17)
    at MultiCouch.stop (/Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/multicouch/lib/multicouch.js:126:10)

Error: not_found
deleted
    at IncomingMessage.<anonymous> (/Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/hoodie-plugins-api/node_modules/couchr/couchr-node.js:168:35)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)

Error: Expected 9 assertions, 27 ran
    at test.done (/Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/lib/types.js:121:25)
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/lib/core.js:218:25
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/deps/async.js:168:13
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/deps/async.js:131:25
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/deps/async.js:165:17
    at /Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/nodeunit/deps/async.js:463:34
    at MultiCouch.<anonymous> (/Users/jan/Work/hoodie/hoodie-plugins-manager/test/lib/utils.js:30:9)
    at MultiCouch.g (events.js:180:16)
    at MultiCouch.emit (events.js:92:17)
    at MultiCouch.stop (/Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/multicouch/lib/multicouch.js:126:10)

Error: conflict
Document update conflict.
    at IncomingMessage.<anonymous> (/Users/jan/Work/hoodie/hoodie-plugins-manager/node_modules/hoodie-plugins-api/node_modules/couchr/couchr-node.js:168:35)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)


FAILURES: 8/82 assertions failed (8250ms)

FAILURES: Undone tests (or their setups/teardowns): 
- unprocessed tasks should be handled on addSource

To fix this, make sure all tests call test.done()
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by janl** [comment]
@caolan do you have any idea about what could be going on here?

**Comment by janl** [comment]
I tried disabling the failing test(s), but now the tests just hang after the `✔ trigger task events in plugins` test.

Also, fwiw, on Linux I see `✖ #1 multiple addSource calls AssertionError: 2 == 1` instead of `3 == 1`.

**Comment by janl** [comment]
disabled all tests and released master as 0.4.0 as testing locally everything seemed to work, but now it looks like signUp is broken in my-first-hoodie, the user gets created and db set up, but the sign up modal displays an error `[object Object]`. If we can get this resolved today, I’ll revert the version bump.

**Comment by caolan** [comment]
I just tried running `npm test` locally for 0.2.6 and the tests passed. What version of CouchDB are you running? It uses multi-couch for the tests.

**Comment by janl** [comment]
Can you try master-1?

I can’t even get 0.2.6 to run.

This is on CouchDB 1.6.1.

**Comment by janl** [comment]
> node --version
v0.10.36

if it helps any

**Comment by janl** [comment]
here’s a log from a fresh 0.2.6 checkout:

```
> git clean -fdx
> git checkout 0.2.6
> npm install
> npm test

> hoodie-plugins-manager@0.2.6 test /Users/jan/Work/hoodie/hoodie-plugins-manager
> nodeunit test


test-plugin-api
✔ changed docs passed to plugins can be modified
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
✔ sendEmail function
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
✔ get config values from plugin manager
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
✔ automatically update plugin config
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
✔ automatically update app config
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
✔ trigger account events in plugins
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
✔ trigger task events in plugins
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
✔ task add events
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
[db_updates] Error: connect ECONNREFUSED
```

it just hangs after this.

**Comment by janl** [comment]
same on linux fwiw

**Comment by janl** [comment]
linux on 1.5.0 :)

**Comment by christophwitzko** [comment]
Refactored and updated the test setup in #20.
The issues should now be resolved.
